ALTER TABLE public.offer_profiles
  ADD COLUMN IF NOT EXISTS industry TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS competitors TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS market_sophistication TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS market_awareness TEXT NOT NULL DEFAULT '';